### ISSUE TITLE
Transpile source code before publishing

### ISSUE THREAD

**Issue by hampusohlsson** [farwayer/mobx-decorators#1]
Hey @farwayer, my app throws an error about decorators in your source.

```
ERROR in ./~/mobx-decorators/index.js
Unexpected character '@' (11:6)
```

Since your module get placed inside my `node_modules` when I install it (which babel is/should be excluding), you would have to transpile your source code before publishing your package to npm.

Otherwise, library looks very useful! Looking forward to try it out 😄

**Comment by farwayer** [comment]
@hampusohlsson thank you for reporting!

But what is reason to transpile decorators in library source if you are planing to use decorators in you own code and you need to transpile in any case? Do I miss something? When do you have this error?

**Comment by hampusohlsson** [comment]
Sure! The first reason to transpile your source code is that you can develop your library using any fancy features you like (ES6/7, decorators etc) but not requiring your end users to use the same. Second, even if I do use those features and babel for *my* source code, I should never have to transpile anything inside node_modules - it would be very expensive and slow.

**Comment by hampusohlsson** [comment]
PS Take a look at some of the installed modules inside your `node_modules` folder. They usually have a `lib` folder or similar where all code is transpiled :)

**Comment by farwayer** [comment]
It sounds sensible. I will publish transpiled version in next release.
