### ISSUE TITLE
Compile errors after 4.0.1 upgrade

### ISSUE THREAD

**Issue by brandonhall** [farwayer/mobx-decorators#12]
I've seen this on two different repos and it's related to the `@babel/proposal-export-default-from` proposal that was added in `4.0.0`. Oddly, I added handling to the my webpack config to match your config and its still not working correctly.

Error: 
![image 2018-04-03 at 10 47 58 am](https://user-images.githubusercontent.com/1144477/38256510-7ed957bc-372c-11e8-8e8d-63b4b6bfa16b.png)

webpack config after changes:
```
          loader: 'babel-loader',
          options: {
            presets: [
              '@babel/preset-react',
              ['@babel/preset-env', { shippedProposals: true, }],
              '@babel/preset-stage-1',
            ],
            plugins: [
              'react-hot-loader/babel',
              'transform-decorators-legacy',
              [
                'transform-class-properties', { loose: true, },
              ],
              '@babel/proposal-export-default-from',
            ],
```
My guess is that `babel-loader` is the issue.

**Comment by farwayer** [comment]
@brandonhall try 4.1.0 please

**Comment by brandonhall** [comment]
Thanks @farwayer, I'll close this and post back if we're still having problems.
