### ISSUE TITLE
Don't set properties to null if they're not present in storage

### ISSUE THREAD

**Issue by zocky** [farwayer/mobx-decorators#13]
Currently, it seems that properties that have default values are still set to null if nothing is loaded from storage. So the following code will throw an error, unless there is an array value already in storage.

````
....
@save
@obsevable myArray = [];
....

@computed get myMappedArray() {
   return myArray.map(....)
}
````

It would be preferable to leave the default value alone if the storage returns nothing.

**Comment by farwayer** [comment]
@zocky Thanks for reporting! Can you try 5.0.0 version please?
