### ISSUE TITLE
Enable esmodules of @babel/preset-env will break the uglifyjs.

### ISSUE THREAD

**Issue by blade254353074** [farwayer/mobx-decorators#17]
webpack build result:
![image](https://user-images.githubusercontent.com/9346008/45734506-659f2b80-bc17-11e8-8b01-6f0f74f85f87.png)

⤵️ `mobx-decorators/esm/utils/decorate.js`
```javascript
export function decorate(withArgs, args, decorator) {
  return withArgs ? decorator : decorator(...args);
                                          ^ Unexpected token: punc (.)
}
// ...
```
We can do:
![image](https://user-images.githubusercontent.com/9346008/45735220-ac8e2080-bc19-11e8-8d34-0a4405b71dbe.png)

**Comment by howells** [comment]
I'm having this problem, do you know how we can resolve it?

**Comment by blade254353074** [comment]
> I'm having this problem, do you know how we can resolve it?

I just removed the `mobx-decorators`......

**Comment by howells** [comment]
Me too 😐

**Comment by farwayer** [comment]
Hi guys. Sorry for delay. I'll fix it when I have some free time.

**Comment by blade254353074** [comment]
Okay, thanks.

**Comment by farwayer** [comment]
Can you try 5.0.3 version please?

**Comment by blade254353074** [comment]
I'll try it later, thanks,
