### ISSUE TITLE
Module not found: Error: Can't resolve 'mobx/package' in '/..../node_modules/mobx-decorators/esm/utils'

### ISSUE THREAD

**Issue by howells** [farwayer/mobx-decorators#19]
Just updated to 5.0.5 and I now get this error:

`Module not found: Error: Can't resolve 'mobx/package' in '/..../node_modules/mobx-decorators/esm/utils'`

Any ideas?

**Comment by farwayer** [comment]
Sorry, look like missed something in build. Will fix today. Use 5.0.3
before please

**Comment by howells** [comment]
No probs, thanks!
