### ISSUE TITLE
Version 2.3.0 in npm is broken

### ISSUE THREAD

**Issue by jasonk** [farwayer/mobx-decorators#5]
It appears that version 2.3.0 isn't installable from npm.  What I found is that when using it I get errors that require can't resolve all of the implementation files (`./setter`, `./toggle`, `./intercept`, etc).  Looking at the contents of the tarfile for the 2.3.0 release versus the 2.2.4 release, both releases contains both `src` and `lib` directories (not sure if that was intentional, if it wasn't you probably want to put `src` in your `.npmignore` file), but while the 2.2.4 release has a transpiled version of every file in src also found in lib, the 2.3.0 release only has a transpiled version of `index.js` and all the other files are missing.

I'm guessing that whoever is publishing the release has upgraded to npm v5.  There were a lot of changes to the publish workflow in npm v5, and if I clone your repo and just run `npm pack` to build a tarfile the same way publish would, I end up with an empty lib directory too.

If that is the problem, the good news is that it's a simple fix.  If you are using npm v5 to publish, you just need to modify your `package.json` file and change the `publish` script to be named `prepack` instead.

**Comment by farwayer** [comment]
Wow @jasonk big thanks for reporting. Fixed.
