### ISSUE TITLE
@save is not loaded after App was hot reloaded

### ISSUE THREAD

**Issue by croogie** [farwayer/mobx-decorators#7]
I've set callbacks `onInitialized`, `onSaved` and `onLoaded` but none of them was called after app has been hotreloaded so I think that store values were not restored from storage. 

Maybe I have to force those values to be loaded somehow?
I see that store constructor is called but nothing else.

**Comment by croogie** [comment]
Few more details about this behaviour.

The problem appears only when I change file with JSX. When I change store code everything is working as expected.

Workaround for it is setting store property as defined:
```javascript
class UserStore {
  storeName = 'user'

  @save({ storage: sessionStorage })
  @observable
  token = JSON.parse(sessionStorage.getItem('user:token'))

  // ...
}
```

**Comment by farwayer** [comment]
Do you access saved property from somewhere? `@save` is  lazy decorator and value will be loaded only after first property access. If you need instant loading you can read property from store constructor:
```js
class UserStore {
  storeName = 'user'

  @save({ storage: sessionStorage })
  @observable
  token = null;

  constructor() {
    this.token;
  }
}
```
