### ISSUE TITLE
@save could use constructor.name as storeName if not explicitly provided

### ISSUE THREAD

**Issue by jayalfredprufrock** [farwayer/mobx-decorators#8]
First, great set of decorators! Really happy I didn't need to implement @save on my own.

For those of us using ES6 classes, it'd be nice if the @save decorator would try to use `target.constructor.name` as storeName if not provided as an option. Probably would be a one-line change, so let me know if you'd accept a PR.

**Comment by farwayer** [comment]
I thought about it but `constructor.name` is unstable thing and can change after minification. So in the first app version `User` can be transformed to `A` and in the next to `B`. Explicit specification helps all app versions to read from the same store.

**Comment by jayalfredprufrock** [comment]
Yeah I figured that's why you opted not to do it this way. Most minify packages do provide a flag that prevents mangling of class names, which I generally enable for other reasons.

Perhaps a better solution would be to allow storeName to accept a function which gets passed the target so users have a little more control?

**Comment by farwayer** [comment]
In v4 function can be passed to `storeName` option.

```js
const mysave = createSaveDecorator({
  storeName: store => store.constructor.name,
});

class User {
  @mysave @observable loginCount;
}
```
