### ISSUE TITLE
Clarify the discompat with TypeScript

### ISSUE THREAD

**Issue by ozra** [farwayer/mobx-decorators#9]
Me and the current web dev are looking at and discussing different technologies to incorporate into the stack of a new project, so am trying to get an understanding and evaluate different ones. We find MobX with Inferno to be interesting, but are investigating the decorators situation — and also TypeScript — which leads me to wonder what is meant by "Don't work with TypeScript yet (sorry)". For us that have only the birds eye view yet on the techs. Where lies the problem? Irreconcilable syntax? Just an implementation issue?

**Comment by farwayer** [comment]
mobx-decorators is set of helper decorators only. It is not necessary for using MobX. mobx-decorators depends on some internal kitchen of MobX and this kitchen is different for JS and TS. So some logic should be realized separately. In next version I will try to add full TS support.

**Comment by ozra** [comment]
Alright. It seems to work for the frontend dude anyway(?) Because we're using TS, mobx and there's decoratprs all over the place. Forgot to holler, sorry.
